[project]
name = "testing"
version = "0.1.0"
description = "A testing repository"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.6",
    "sphinx>=8.2.3",
    "sphinxcontrib-napoleon>=0.7",
]
